const Dashboard = () => {
  return (
    <div className="bg-gray-100">
      Dashboard
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
      <div>1˝</div>
    </div>
  );
};

export default Dashboard;
